import { useMemo, useState } from 'react';
import { useStore } from '../../store';
import type {
  DistillCandidate,
  DistillKind,
} from '../../services/capture/distillLocal';
import { distillLocal } from '../../services/capture/distillLocal';
import {
  detectAIConversation,
  parsePastedConversation,
  type ParsedConversation,
} from '../../services/capture/PasteCapture';
import { layoutConversationMap } from '../../services/capture/AutoLayout';

export type CaptureSource = 'paste' | 'chatgpt-export';

export type CaptureInput =
  | { source: 'paste'; rawText: string; conversationId: string; landAt: { x: number; y: number } }
  | {
      source: 'chatgpt-export';
      title: string;
      rawText: string;
      conversationId: string;
      landAt: { x: number; y: number };
    };

const KIND_ORDER: DistillKind[] = [
  'decision',
  'task',
  'question',
  'claim',
  'source',
];

const KIND_LABELS: Record<DistillKind, string> = {
  decision: 'Decisions',
  task: 'Tasks',
  question: 'Open questions',
  claim: 'Claims',
  source: 'Sources',
};

/**
 * Plan 41 — Capture Preview. Right-side overlay that shows the parsed
 * conversation title and the candidate nodes generated by the local
 * Distiller (plan 44). The user picks which candidates land on the canvas.
 *
 * No outbound network calls in this component or its dependencies.
 */
export function CapturePreview({
  input,
  onClose,
}: {
  input: CaptureInput;
  onClose: () => void;
}) {
  const addNode = useStore((s) => s.addNode);
  const addEdge = useStore((s) => s.addEdge);
  const setCanvasSelection = useStore((s) => s.setCanvasSelection);

  const parsed: ParsedConversation = useMemo(() => {
    if (input.source === 'chatgpt-export') {
      const inferred = parsePastedConversation(input.rawText);
      return { title: input.title || inferred.title, turns: inferred.turns };
    }
    return parsePastedConversation(input.rawText);
  }, [input]);

  const [titleDraft, setTitleDraft] = useState(parsed.title);
  const candidates: DistillCandidate[] = useMemo(
    () => distillLocal(parsed.turns),
    [parsed],
  );
  // Acceptance is "all candidates checked by default" plus a sparse override
  // map for explicit user toggles. Deriving `accepted` instead of mirroring
  // it in state means we never need a re-sync effect when `candidates` change.
  const [overrides, setOverrides] = useState<Record<string, boolean>>({});
  const accepted = useMemo(() => {
    const set = new Set<string>();
    for (const c of candidates) {
      const override = overrides[c.id];
      if (override === false) continue;
      set.add(c.id);
    }
    return set;
  }, [candidates, overrides]);

  function toggle(id: string) {
    setOverrides((prev) => ({ ...prev, [id]: !accepted.has(id) }));
  }

  function selectAll(kind: DistillKind, value: boolean) {
    setOverrides((prev) => {
      const next = { ...prev };
      for (const c of candidates) {
        if (c.kind !== kind) continue;
        next[c.id] = value;
      }
      return next;
    });
  }

  const grouped: Record<DistillKind, DistillCandidate[]> = useMemo(() => {
    const out: Record<DistillKind, DistillCandidate[]> = {
      decision: [],
      task: [],
      question: [],
      claim: [],
      source: [],
    };
    for (const c of candidates) out[c.kind].push(c);
    return out;
  }, [candidates]);

  function applyToCanvas() {
    const accept = candidates.filter((c) => accepted.has(c.id));

    // Root node carries the conversation title + a 1-line gist.
    const gist = parsed.turns.find((t) => t.role === 'assistant')?.content
      .split('\n')
      .map((s) => s.trim())
      .find((s) => s.length > 0) ?? '';

    const layout = layoutConversationMap(
      input.landAt,
      accept.map((c) => ({ id: c.id, kind: c.kind })),
    );

    const root = addNode({
      conversationId: input.conversationId,
      kind: 'markdown',
      title: titleDraft.trim() || 'Pasted conversation',
      contentMarkdown: `# ${titleDraft.trim() || 'Pasted conversation'}\n\n${gist.slice(0, 600)}`,
      position: layout.rootPosition,
      width: 320,
      height: 180,
      tags: ['hypratia', 'imported'],
    });

    const idMap = new Map<string, string>();
    for (const c of accept) {
      const pos = layout.positions[c.id] ?? { x: input.landAt.x, y: input.landAt.y };
      const created = addNode({
        conversationId: input.conversationId,
        kind: 'markdown',
        title: c.title,
        contentMarkdown: c.body,
        position: pos,
        width: 280,
        height: 140,
        tags: ['hypratia', `kind:${c.kind}`],
      });
      idMap.set(c.id, created.id);
      addEdge({
        sourceNodeId: root.id,
        targetNodeId: created.id,
        ...(c.kind === 'claim' ? {} : { kind: 'related' as const }),
      });
    }

    const newIds = [root.id, ...idMap.values()];
    setCanvasSelection(newIds, []);
    onClose();
  }

  const acceptedCount = accepted.size;

  return (
    <aside
      className="capture-preview"
      role="dialog"
      aria-label="Capture preview"
      onContextMenu={(e) => e.stopPropagation()}
      onPointerDown={(e) => e.stopPropagation()}
    >
      <header className="capture-preview-header">
        <div className="capture-preview-title-row">
          <input
            className="capture-preview-title"
            type="text"
            value={titleDraft}
            onChange={(e) => setTitleDraft(e.target.value)}
            placeholder="Conversation title"
          />
          <button
            type="button"
            className="capture-preview-close"
            onClick={onClose}
            aria-label="Close"
          >
            ×
          </button>
        </div>
        <p className="capture-preview-meta">
          {parsed.turns.length} turn{parsed.turns.length === 1 ? '' : 's'} ·{' '}
          {candidates.length} candidate{candidates.length === 1 ? '' : 's'} ·{' '}
          <span className="capture-preview-pill">Local parse — no network</span>
        </p>
      </header>

      <div className="capture-preview-body">
        {KIND_ORDER.map((kind) => {
          const items = grouped[kind];
          if (items.length === 0) return null;
          const allOn = items.every((c) => accepted.has(c.id));
          return (
            <section key={kind} className="capture-preview-group">
              <header className="capture-preview-group-header">
                <h3>{KIND_LABELS[kind]}</h3>
                <button
                  type="button"
                  className="capture-preview-allnone"
                  onClick={() => selectAll(kind, !allOn)}
                >
                  {allOn ? 'None' : 'All'}
                </button>
              </header>
              <ul className="capture-preview-list">
                {items.map((c) => (
                  <li key={c.id}>
                    <label className="capture-preview-row">
                      <input
                        type="checkbox"
                        checked={accepted.has(c.id)}
                        onChange={() => toggle(c.id)}
                      />
                      <span className="capture-preview-row-title">{c.title}</span>
                    </label>
                  </li>
                ))}
              </ul>
            </section>
          );
        })}
        {candidates.length === 0 ? (
          <p className="capture-preview-empty">
            No structure detected. Try ⌘⇧V to open the preview anyway.
          </p>
        ) : null}
      </div>

      <footer className="capture-preview-footer">
        <button
          type="button"
          className="capture-preview-secondary"
          onClick={onClose}
        >
          Discard
        </button>
        <button
          type="button"
          className="capture-preview-primary"
          onClick={applyToCanvas}
          disabled={acceptedCount === 0 && candidates.length > 0}
        >
          Add {acceptedCount > 0 ? `${acceptedCount} ` : ''}to canvas
        </button>
      </footer>
    </aside>
  );
}

/**
 * Convenience: heuristic decision for whether `text` should auto-trigger the
 * preview on plain ⌘V. ⌘⇧V always opens the preview regardless.
 */
export function shouldOpenCapture(text: string): boolean {
  return detectAIConversation(text).confidence >= 0.6;
}
